### ISSUE TITLE
Suggestions returns non valid emails

### ISSUE THREAD

**Issue by Zaharkov** [verifalia/verifalia-csharp-sdk#4]
On email validation request `suggestions`, what returns in `ValidationEntry`, contains emails what doesn't valid by this own service. If it possible, better return only valid emails (or maybe add some flag in request, to filter only valid emails in response suggestions)

**Comment by verifalia** [comment]
Thanks for your suggestion, @Zaharkov.

As you mentioned, currently our service does not verify the email addresses provided in the suggestions field, and this is intentional: verifying all the suggested emails would require a significant amount of processing time, which users generally cannot afford to wait for. Instead, the primary goal of our suggestions is to assist users who may have made a typo when entering their email address.

That said, we appreciate your suggestion and will consider it for a future release of our email verification service - thank you!

Since this particular request is not related to our .NET SDK (or any specific Verifalia SDK), we are closing this issue to avoid any potential misunderstandings.
